name: dart_fp_pipe
description: A small package that adds support for piping function return values to another function.
version: 0.1.0
repository: https://github.com/jshep23/dart_fp_pipe

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
